apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: electrolytework 
  labels:
    app: electrolytework
spec:
  replicas: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: electrolytework
        tier: nginx
    spec:
      containers:
      - image: jefflaplante/electrolyte.work
        name: electrolytework
        ports:
        - containerPort: 80 
          name: electrolytework
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
