apiVersion: v1
kind: Service
metadata:
  name: electrolytework 
  labels:
    app: electrolytework
spec:
  sessionAffinity: ClientIP
  ports:
    - port: 80
      nodePort: 30502
      targetPort: 80
  type: NodePort
  selector:
    app: electrolytework
    tier: nginx
