apiVersion: v1
kind: Service
metadata:
  name: electrolyte.work 
  labels:
    app: electrolyte.work
spec:
  sessionAffinity: ClientIP
  ports:
    - port: 80
      nodePort: 30501
      targetPort: 80
  type: NodePort
  selector:
    app: electrolyte.work
    tier: nginx
